// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8pPNA-l4WFKXelM3TxuGJqp-ByPE3M4s',
    appId: '1:1085598173623:web:ccbf96b1ba6bca2a774032',
    messagingSenderId: '1085598173623',
    projectId: 'yokatale-70625',
    authDomain: 'yokatale-70625.firebaseapp.com',
    storageBucket: 'yokatale-70625.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi0tTkiPDleVC-3a50L6bGktzyzbFyKBU',
    appId: '1:1085598173623:android:b48ca06dda7e89ca774032',
    messagingSenderId: '1085598173623',
    projectId: 'yokatale-70625',
    storageBucket: 'yokatale-70625.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy-6b3RBDw8cOsaauQUQlt5YrIlk9Sbn0',
    appId: '1:1085598173623:ios:19e00ea9003d3909774032',
    messagingSenderId: '1085598173623',
    projectId: 'yokatale-70625',
    storageBucket: 'yokatale-70625.appspot.com',
    iosClientId: '1085598173623-4gfc1snepuk60thsuqonrlufg1dlfhk9.apps.googleusercontent.com',
    iosBundleId: 'com.example.yookatale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy-6b3RBDw8cOsaauQUQlt5YrIlk9Sbn0',
    appId: '1:1085598173623:ios:8ef335d110d5076c774032',
    messagingSenderId: '1085598173623',
    projectId: 'yokatale-70625',
    storageBucket: 'yokatale-70625.appspot.com',
    iosClientId: '1085598173623-8qnq7colp5ag7k9bpjflss0bj46lv1ec.apps.googleusercontent.com',
    iosBundleId: 'com.example.yookatale.RunnerTests',
  );
}
