// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-7kaqMQSnWTywa0oz3IfMWPP7yS6GrJA',
    appId: '1:1091927934214:web:5898dcf958cacc4af0ca87',
    messagingSenderId: '1091927934214',
    projectId: 'yookatale-aa476',
    authDomain: 'yookatale-aa476.firebaseapp.com',
    storageBucket: 'yookatale-aa476.appspot.com',
    measurementId: 'G-V89W3PMDKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGWEgCpdgM2qeHkmPmKN9ikWHWexb_UpY',
    appId: '1:1091927934214:android:7f728f56c7a683d7f0ca87',
    messagingSenderId: '1091927934214',
    projectId: 'yookatale-aa476',
    storageBucket: 'yookatale-aa476.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxCo2bbbzuS3khclVY1aAdD7-cW0M7xO8',
    appId: '1:1091927934214:ios:6c76d679ec45ce88f0ca87',
    messagingSenderId: '1091927934214',
    projectId: 'yookatale-aa476',
    storageBucket: 'yookatale-aa476.appspot.com',
    iosClientId: '1091927934214-fujsu0oqkpsdoaglifar4ut2tu8hiha8.apps.googleusercontent.com',
    iosBundleId: 'com.example.yookatale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxCo2bbbzuS3khclVY1aAdD7-cW0M7xO8',
    appId: '1:1091927934214:ios:228b898a4faea7fbf0ca87',
    messagingSenderId: '1091927934214',
    projectId: 'yookatale-aa476',
    storageBucket: 'yookatale-aa476.appspot.com',
    iosClientId: '1091927934214-d25rn2aa9ntoar55cuvnmgnkeu79kr9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.yookatale.RunnerTests',
  );
}
